### ISSUE TITLE
Cannot deploy demo app

### ISSUE THREAD

**Issue by rgormley** [banzaicloud/backyards-cli#107]
**Describe the bug**
Demo app never finishes installation.

**Steps to reproduce the issue:**

1. Install fresh cluster on AWS via `kops` and await successful cluster validation
2. Execute install command (`backyards install -a --run-demo`):

```
INFO[0036] deployment.apps:backyards-demo/frontpage-v1 - pending
error during demo application install: timed out waiting for the condition
```

3. Retry install command (which notes many components are configured and/or unchanged. Get same error.

**Expected behavior**
Demo app installs per documentation.

**Comment by waynz0r** [comment]
@rgormley, thanks for opening the issue!

That timeout is usually caused by not enough resources, can you please check the pods in the `backyards-demo` namespace with kubectl?

**Comment by rgormley** [comment]
I was able to get things started by adjusting `kops` node configuration to 3 x `t3.large` so all good - perhaps a note on minimum requirements is all that is needed?

**Comment by Laci21** [comment]
Minimum resource requirements are documented in the Backyards docs under this section: https://banzaicloud.com/docs/backyards/quickstart/#creating-a-test-cluster

I've just created a PR (merged already) to have the documentation link present in this repo's README.md for easier access.
